package com.kaiser.aiagent.data.memory

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A single unit of long-term memory. v0.3 supports only manual storage
 * — the agent does not yet auto-generate memories. Future versions
 * will add automatic extraction and retrieval.
 *
 * Memory entries are immutable once created (use delete + re-create to
 * "update"). This keeps the persistence layer simple.
 *
 * @property id Stable UUID. Generated by [MemoryRepository.add].
 * @property type Free-form category. v0.3 uses: "fact", "preference",
 *   "note". Future versions can extend.
 * @property content Free-form text. May be JSON-encoded structured data
 *   if the source tool prefers that.
 * @property source Where the memory came from. v0.3 uses "manual".
 *   Future: "auto:chat-extraction", "auto:tool-result", etc.
 * @property createdAt Epoch milliseconds.
 * @property tags Optional list of free-form tags for future search.
 */
@Serializable
data class MemoryEntry(
    val id: String,
    val type: String,
    val content: String,
    val source: String = "manual",
    @SerialName("created_at") val createdAt: Long,
    val tags: List<String> = emptyList()
)
