package com.kaiser.aiagent.data.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Role of a chat message. Mirrors the OpenAI chat-completions role
 * values plus a `tool` role for tool-call results.
 */
@Serializable
enum class MessageRole {
    @SerialName("user") USER,
    @SerialName("assistant") ASSISTANT,
    @SerialName("tool") TOOL,
    @SerialName("system") SYSTEM;

    fun toAiRole(): String = when (this) {
        USER -> "user"
        ASSISTANT -> "assistant"
        TOOL -> "tool"
        SYSTEM -> "system"
    }
}

/**
 * A single persisted chat message. Belongs to exactly one
 * [ConversationEntity]. v0.3 stores all messages in the conversation
 * file; v0.4 can split to Room for queryability.
 */
@Serializable
data class MessageEntity(
    val id: String,
    val role: MessageRole,
    val content: String,
    @SerialName("created_at") val createdAt: Long,
    /** True if this message was generated by a tool call (role=tool). */
    val isToolResult: Boolean = false,
    /** Name of the tool that produced this message, if applicable. */
    val toolName: String? = null
)

/**
 * A persisted conversation. v0.3 stores each conversation as a single
 * JSON file under `filesDir/conversations/{id}.json`.
 */
@Serializable
data class ConversationEntity(
    val id: String,
    val title: String,
    @SerialName("created_at") val createdAt: Long,
    @SerialName("updated_at") val updatedAt: Long,
    val messages: List<MessageEntity> = emptyList()
)
